# Generated by Django 6.0 on 2025-12-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero de mesa')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Plato',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='pendiente', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de plato')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
    ]
