# Generated by Django 6.0 on 2025-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesa_rename_producto_plato_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='talla',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande'), ('U', 'Unico')], default='U', max_length=1, verbose_name='Tamaño'),
        ),
    ]
