# Generated by Django 6.0 on 2025-12-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
            preserve_default=False,
        ),
    ]
