# Generated by Django 6.0 on 2025-12-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plato_categorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='categorio',
            new_name='categoria',
        ),
    ]
